# These are supported funding model platforms

github: barabazs 
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: barabazs
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: ["https://etherscan.io/address/0x6b78d3deea258914C2f4e44054d22094107407e5","https://www.blockchain.com/btc/address/bc1qvvh8s3tt97cwy20mfdttpwqw0vgsrrceq8zkmw"]
